basic_auth:
  user: team73a
  pass: frm73a

tpEQjRTKddczgdO7FOSaMFip1cUylIv+1dTwYNfg7DuA2o6AVf6g0LW+c6UNwOMQZk/FegKCQPHeEML8JGD0O84jFtXu0DodIMpxGyVdG8e6jtZ7onKx3aspyyZUUi7OOK0Y7kjb7o8+M6vvDiiZW96htbqSVjcT5Q993CgGN0Jbz6WvXRA6XOiPWFUAPhNRMa5MzTZpHOPrr1NGJKeia/rj5+dK9rpYl7J9ZuWrjx2QQepi9GCNkQuoJMSROpijgx2CFt3A8pbEHiaLHjQqAarwm6+ahu+aS7Ww3d9IIwUngN41YQbyieY4g2nnk3znWu2eZj32h6BU30roiWZSjdytiv7vajP9vzjaO9VaNFlXeaekM/Y9edrr33hemqzEzTpqeMPHlPfQbzK8ELN/qIUd9ndZRd0P2oe2--I6a+Jc0rke2cwZMC--TWw2I/nT9Ds8Ved8oZ8q6g==
